version: "3"
services:
  log:
    build: ./log
    container_name: log
    ports:
      - 5001:5000
    volumes:
      - ./log:/app
  notes:
    build: ./notes
    container_name: notes
    ports:
      - 5002:5000
    volumes:
      - ./notes:/app
  catalogue:
    build: ./catalogue
    container_name: catalogue
    ports:
      - 5003:5000
    volumes:
      - ./catalogue:/app
  search:
    build: ./search
    container_name: search
    ports:
      - 5000:5000
    volumes:
      - ./search:/app
