version: '3'

services:
    mongodb_container:
        container_name: mongodb
        image: mongo:4.2.3-bionic
        expose:
            - 27017
        ports: 
            - 27017:27017
    search:
        build: ./search
        container_name: search
        restart: always
        ports: 
            - 5000:5000
        # volumes:
        #     - ./search:/app
    log:
        build: ./log
        container_name: log
        restart: always
        ports: 
            - 5001:5000
        # volumes:
        #     - ./log:/app
    notes:
        build: ./notes
        container_name: notes
        restart: always
        ports: 
            - 5002:5000
        # volumes:
        #     - ./notes:/app
    catalogue:
        build: ./catalogue
        container_name: catalogue
        restart: always
        ports: 
            - 5003:5000
        # volumes:
        #     - ./catalogue:/app